name: CI/CD workflow for Maven Build and Sonar Code scan
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'
    - name: Build with Maven
      run: mvn clean install -f aspire-casestudy1-demo/pom.xml
      
    - name: SonarQube Scan    
      uses: SonarSource/sonarcloud-github-action@master
      #uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}      
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=praveenkumar011
          -Dsonar.projectKey=praveenkumar011_aspire-casestudy1-demo          
          -Dsonar.sources=aspire-casestudy1-demo/src
          -Dsonar.java.binaries=aspire-casestudy1-demo/target/classes
     
    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
  
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/aspire-casestudy1-demo:latest aspire-casestudy1-demo

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/aspire-casestudy1-demo:late

