name: CI/CD workflow for Maven Build and Sonar Code scan
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'
    - name: Build with Maven
      run: mvn clean install -f aspire-casestudy1-demo/pom.xml
    - name: SonarQube Scan    
      #uses: SonarSource/sonarcloud-github-action@master
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_TOKEN: ${{ secrets.GIT_TOKEN }}
        #sonarqube token sqa_6dc9f3a8fb24435780408e0a98b2779523942fec
        # cloud 9d888d933d4caa8163e00cb122cbdd88550acc23

      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=praveenkumar011
          -Dsonar.projectKey=aspire-casestudy1-demo
  
